apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-model-rs-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: release-model
  template:
    metadata:
      labels:
        app: release-model
    spec:
      containers:
      - name: release-model
        image: group02-release-model-service:latest
        imagePullPolicy: Never
            