apiVersion: apps/v1
kind: Deployment
metadata:
  name: artist-logic-rs-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: artist-logic
  template:
    metadata:
      labels:
        app: artist-logic
    spec:
      imagePullSecrets:
      - name: docker-cred
      containers:
      - name: artist-logic
        image: guilhermedsantos/cn_group02:artistlogic
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        env:
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: json-key
              key: API_TOKEN
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/health"
            port: 5001
        livenessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/health"
            port: 5001
        startupProbe:
          httpGet:
            path: "/health"
            port: 5001
          failureThreshold: 5
          periodSeconds: 10 
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: artist-model-rs-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: artist-model
  template:
    metadata:
      labels:
        app: artist-model
    spec:
      imagePullSecrets:
      - name: docker-cred
      containers:
      - name: artist-model
        image: guilhermedsantos/cn_group02:artistmodel
        imagePullPolicy: Always
        env:
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: json-key
              key: API_TOKEN
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50052
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50052
        startupProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50052
          failureThreshold: 5
          periodSeconds: 10    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: artists-releases-model-rs-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: artists-releases-model
  template:
    metadata:
      labels:
        app: artists-releases-model
    spec:
      imagePullSecrets:
      - name: docker-cred
      containers:
      - name: artists-releases-model
        image: guilhermedsantos/cn_group02:artistsreleasesmodel
        imagePullPolicy: Always
        env:
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: json-key
              key: API_TOKEN
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50053
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50053
        startupProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50053
          failureThreshold: 5
          periodSeconds: 10
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: artists-tracks-model-rs-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: artists-tracks-model
  template:
    metadata:
      labels:
        app: artists-tracks-model
    spec:
      imagePullSecrets:
      - name: docker-cred
      containers:
      - name: artists-tracks-model
        image: guilhermedsantos/cn_group02:artiststracksmodel
        imagePullPolicy: Always
        env:
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: json-key
              key: API_TOKEN
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50054
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50054
        startupProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50054
          failureThreshold: 5
          periodSeconds: 10    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: genre-logic-rs-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: genre-logic
  template:
    metadata:
      labels:
        app: genre-logic
    spec:
      imagePullSecrets:
      - name: docker-cred
      containers:
      - name: genre-logic
        image: guilhermedsantos/cn_group02:genrelogic
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        env:
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: json-key
              key: API_TOKEN
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/health"
            port: 5002
        livenessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/health"
            port: 5002
        startupProbe:
          httpGet:
            path: "/health"
            port: 5002
          failureThreshold: 5
          periodSeconds: 10
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: genre-model-rs-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: genre-model
  template:
    metadata:
      labels:
        app: genre-model
    spec:
      imagePullSecrets:
      - name: docker-cred
      containers:
      - name: genre-model
        image: guilhermedsantos/cn_group02:genremodel
        imagePullPolicy: Always
        env:
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: json-key
              key: API_TOKEN
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50055
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50055
        startupProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50055
          failureThreshold: 5
          periodSeconds: 10
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-logic-rs-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: playlist-logic
  template:
    metadata:
      labels:
        app: playlist-logic
    spec:
      imagePullSecrets:
      - name: docker-cred
      containers:
      - name: playlist-logic
        image: guilhermedsantos/cn_group02:playlistlogic
        imagePullPolicy: Always
        ports:
        - containerPort: 5003
        env:
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: json-key
              key: API_TOKEN
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/health"
            port: 5003
        livenessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/health"
            port: 5003
        startupProbe:
          httpGet:
            path: "/health"
            port: 5003
          failureThreshold: 5
          periodSeconds: 10
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-model-rs-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: playlist-model
  template:
    metadata:
      labels:
        app: playlist-model
    spec:
      imagePullSecrets:
      - name: docker-cred
      containers:
      - name: playlist-model
        image: guilhermedsantos/cn_group02:playlistmodel
        imagePullPolicy: Always
        env:
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: json-key
              key: API_TOKEN
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50057
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50057
        startupProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50057
          failureThreshold: 5
          periodSeconds: 10    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-logic-rs-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: release-logic
  template:
    metadata:
      labels:
        app: release-logic
    spec:
      imagePullSecrets:
      - name: docker-cred
      containers:
      - name: release-logic
        image: guilhermedsantos/cn_group02:releaselogic
        imagePullPolicy: Always
        ports:
        - containerPort: 5004
        env:
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: json-key
              key: API_TOKEN
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/health"
            port: 5004
        livenessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/health"
            port: 5004
        startupProbe:
          httpGet:
            path: "/health"
            port: 5004
          failureThreshold: 5
          periodSeconds: 10
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-model-rs-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: release-model
  template:
    metadata:
      labels:
        app: release-model
    spec:
      imagePullSecrets:
      - name: docker-cred
      containers:
      - name: release-model
        image: guilhermedsantos/cn_group02:releasemodel
        imagePullPolicy: Always
        env:
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: json-key
              key: API_TOKEN
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50058
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50058
        startupProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50058
          failureThreshold: 5
          periodSeconds: 10    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: track-logic-rs-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: track-logic
  template:
    metadata:
      labels:
        app: track-logic
    spec:
      imagePullSecrets:
      - name: docker-cred
      containers:
      - name: track-logic
        image: guilhermedsantos/cn_group02:tracklogic
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: json-key
              key: API_TOKEN
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/health"
            port: 5000
        livenessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/health"
            port: 5000
        startupProbe:
          httpGet:
            path: "/health"
            port: 5000
          failureThreshold: 5
          periodSeconds: 10
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: track-model-rs-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: track-model
  template:
    metadata:
      labels:
        app: track-model
    spec:
      imagePullSecrets:
      - name: docker-cred
      containers:
      - name: track-model
        image: guilhermedsantos/cn_group02:trackmodel
        imagePullPolicy: Always
        env:
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: json-key
              key: API_TOKEN
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50051
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50051
        startupProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:50051
          failureThreshold: 5
          periodSeconds: 10   

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-rs-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-logic
  template:
    metadata:
      labels:
        app: auth-logic
    spec:
      imagePullSecrets:
      - name: docker-cred
      containers:
      - name: auth-logic
        image: guilhermedsantos/cn_group02:auth
        imagePullPolicy: Always
        ports:
        - containerPort: 5055
        env:
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: json-key
              key: API_TOKEN
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/health"
            port: 5055
        livenessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/health"
            port: 5055
        startupProbe:
          httpGet:
            path: "/health"
            port: 5055
          failureThreshold: 5
          periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: auth-logic-rs-3
spec:
  selector:
    app: auth-logic
  ports:
    - protocol: TCP
      port: 5055
      targetPort: 5055

---

apiVersion: v1
kind: Service
metadata:
  name: track-logic-rs-3
spec:
  selector:
    app: track-logic
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: artist-logic-rs-3
spec:
  selector:
    app: artist-logic
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: genre-logic-rs-3
spec:
  selector:
    app: genre-logic
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: playlist-logic-rs-3
spec:
  selector:
    app: playlist-logic
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: release-logic-rs-3
spec:
  selector:
    app: release-logic
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://group02.cn.com/api/auth/token/validate"
    nginx.ingress.kubernetes.io/auth-signin: "https://group02.cn.com/api/auth/login"
    nginx.ingress.kubernetes.io/auth-response-headers: "authorization"
spec:
  rules:
  - host: group02.cn.com
    http:
      paths:
      - pathType: Prefix
        path: "/api/tracks"
        backend:
          service:
            name: track-logic-rs-3
            port:
              number: 5000
      - pathType: Prefix
        path: "/api/artists"
        backend:
          service:
            name: artist-logic-rs-3
            port:
              number: 5001
      - pathType: Prefix
        path: "/api/genres"
        backend:
          service:
            name: genre-logic-rs-3
            port:
              number: 5002
      - pathType: Prefix
        path: "/api/playlists"
        backend:
          service:
            name: playlist-logic-rs-3
            port:
              number: 5003
      - pathType: Prefix
        path: "/api/releases"
        backend:
          service:
            name: release-logic-rs-3
            port:
              number: 5004 