version: "3.8"

services:
  # ARTIST
  artist-logic-service:
    build:
      context: .
      dockerfile: ./app/artist-logic-service/Dockerfile
    container_name: artist-logic-service
    environment:
      ARTIST_HOST: artist-model-service
    ports:
      - "5001:5001"
    networks:
      idc-net:
        ipv4_address: 172.100.10.5
    depends_on:
      - artist-model-service

  artist-model-service:
    build:
      context: .
      dockerfile: ./app/artist-model-service/Dockerfile
    container_name: artist-model-service
    environment:
      POSTGRES_HOST: ${POSTGRES_ARTIST_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      idc-net:
        ipv4_address: 172.100.10.6
    depends_on:
      - artist-db

  artist-db:
    container_name: artist-db
    build:
      context: .
      dockerfile: ./model/artist/Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5434:5432
    volumes:
      - artist-data:/var/lib/postgresql/data
    networks:
      idc-net:
        ipv4_address: 172.100.10.7

  # GENRE
  genre-logic-service:
    build:
      context: .
      dockerfile: ./app/genre-logic-service/Dockerfile
    container_name: genre-logic-service
    environment:
      TRACK_HOST: track-model-service
      GENRE_HOST: genre-model-service
    ports:
      - "5002:5002"
    networks:
      idc-net:
        ipv4_address: 172.100.10.8
    depends_on:
      - genre-model-service

  genre-model-service:
    build:
      context: .
      dockerfile: ./app/genre-model-service/Dockerfile
    container_name: genre-model-service
    environment:
      POSTGRES_HOST: ${POSTGRES_GENRE_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      idc-net:
        ipv4_address: 172.100.10.9
    depends_on:
      - genre-db

  genre-db:
    container_name: genre-db
    build:
      context: .
      dockerfile: ./model/genre/Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5435:5432
    volumes:
      - genre-data:/var/lib/postgresql/data
    networks:
      idc-net:
        ipv4_address: 172.100.10.10

  # TRACK
  track-logic-service:
    build:
      context: .
      dockerfile: ./app/track-logic-service/Dockerfile
    container_name: track-logic-service
    environment:
      TRACK_HOST: track-model-service
      GENRE_HOST: genre-model-service
#     RELEASE_HOST: release-model-service
    ports:
      - "5000:5000"
    networks:
      idc-net:
        ipv4_address: 172.100.10.2
    depends_on:
      - track-model-service

  track-model-service:
    build:
      context: .
      dockerfile: ./app/track-model-service/Dockerfile
    container_name: track-model-service
    environment:
      POSTGRES_HOST: ${POSTGRES_TRACK_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      idc-net:
        ipv4_address: 172.100.10.3
    depends_on:
      - track-db

  track-db:
    container_name: track-db
    build:
      context: .
      dockerfile: ./model/track/Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - track-data:/var/lib/postgresql/data
    networks:
      idc-net:
        ipv4_address: 172.100.10.4

  playlist-logic-service:
    build:
      context: .
      dockerfile: ./app/playlist-logic-service/Dockerfile
    container_name: playlist-logic-service
    environment:
      PLAYLIST_HOST: playlist-model-service
      TRACK_HOST: track-model-service
    ports:
      - "5003:5003"
    networks:
      idc-net:
        ipv4_address: 172.100.10.11
    depends_on:
      - playlist-model-service

  playlist-model-service:
    build:
      context: .
      dockerfile: ./app/playlist-model-service/Dockerfile
    container_name: playlist-model-service
    environment:
      POSTGRES_HOST: ${POSTGRES_PLAYLIST_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      idc-net:
        ipv4_address: 172.100.10.12
    depends_on:
      - playlist-db

  playlist-db:
    container_name: playlist-db
    build:
      context: .
      dockerfile: ./model/playlist/Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5436:5432
    volumes:
      - playlist-data:/var/lib/postgresql/data
    networks:
      idc-net:
        ipv4_address: 172.100.10.13

volumes:
  artist-data:
  genre-data:
  track-data:

networks:
  idc-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.100.10.0/24
