# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: track.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btrack.proto\"\xcc\x01\n\x05Track\x12\x10\n\x08track_id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0b\n\x03mix\x18\x03 \x01(\t\x12\x12\n\nis_remixed\x18\x04 \x01(\x08\x12\x12\n\nrelease_id\x18\x05 \x01(\x05\x12\x14\n\x0crelease_date\x18\x06 \x01(\t\x12\x10\n\x08genre_id\x18\x07 \x01(\x05\x12\x13\n\x0bsubgenre_id\x18\x08 \x01(\x05\x12\x11\n\ttrack_url\x18\t \x01(\t\x12\x0b\n\x03\x62pm\x18\n \x01(\x05\x12\x10\n\x08\x64uration\x18\x0b \x01(\x05\"#\n\x0fGetTrackRequest\x12\x10\n\x08track_id\x18\x01 \x01(\x05\")\n\x10GetTrackResponse\x12\x15\n\x05track\x18\x01 \x01(\x0b\x32\x06.Track2?\n\x0cTrackService\x12/\n\x08getTrack\x12\x10.GetTrackRequest\x1a\x11.GetTrackResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'track_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRACK']._serialized_start=16
  _globals['_TRACK']._serialized_end=220
  _globals['_GETTRACKREQUEST']._serialized_start=222
  _globals['_GETTRACKREQUEST']._serialized_end=257
  _globals['_GETTRACKRESPONSE']._serialized_start=259
  _globals['_GETTRACKRESPONSE']._serialized_end=300
  _globals['_TRACKSERVICE']._serialized_start=302
  _globals['_TRACKSERVICE']._serialized_end=365
# @@protoc_insertion_point(module_scope)
