apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-logic-rs-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: release-logic
  template:
    metadata:
      labels:
        app: release-logic
    spec:
      containers:
      - name: release-logic
        image: group02-release-logic-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5004