apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingress-gateway  
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: istio-ingressgateway-certs # must be the same as secret
    hosts:
    - "*"

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: track-istio
spec:
  hosts:
  - "*"
  gateways:
  - ingress-gateway
  http:
  - match:
    - uri:
        prefix: /api/tracks
    route:
    - destination:
        port:
          number: 5000
        host: track-logic
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: artists-istio
spec:
  hosts:
  - "*"
  gateways:
  - ingress-gateway
  http:
  - match:
    - uri:
        prefix: /api/artists
    route:
    - destination:
        port:
          number: 5001
        host: artist-logic
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: genre-istio  
spec:
  hosts:
  - "*"
  gateways:
  - ingress-gateway
  http:
  - match:
    - uri:
        prefix: /api/genres
    route:
    - destination:
        port:
          number: 5002
        host: genre-logic
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: playlist-istio
spec:
  hosts:
  - "*"
  gateways:
  - ingress-gateway
  http:
  - match:
    - uri:
        prefix: /api/playlists
    route:
    - destination:
        port:
          number: 5003
        host: playlist-logic
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: release-istio 
spec:
  hosts:
  - "*"
  gateways:
  - ingress-gateway
  http:
  - match:
    - uri:
        prefix: /api/releases
    route:
    - destination:
        port:
          number: 5004
        host: release-logic