apiVersion: apps/v1
kind: Deployment
metadata:
  name: artist-model-rs-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: artist-model
  template:
    metadata:
      labels:
        app: artist-model
    spec:
      containers:
      - name: artist-model
        image: group02-artist-model-service:latest
        imagePullPolicy: Never
       
     

