apiVersion: apps/v1
kind: Deployment
metadata:
  name: artists-tracks-model-rs-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: artists-tracks-model
  template:
    metadata:
      labels:
        app: artists-tracks-model
    spec:
      containers:
      - name: artists-tracks-model
        image: group02-artists-tracks-model-service:latest
        imagePullPolicy: Never
       
            