# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import artist_pb2 as artist__pb2


class ArtistServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getArtist = channel.unary_unary(
                '/ArtistService/getArtist',
                request_serializer=artist__pb2.GetArtistRequest.SerializeToString,
                response_deserializer=artist__pb2.GetArtistResponse.FromString,
                )
        self.addArtist = channel.unary_unary(
                '/ArtistService/addArtist',
                request_serializer=artist__pb2.AddArtistRequest.SerializeToString,
                response_deserializer=artist__pb2.AddArtistResponse.FromString,
                )
        self.addTrgetArtistReleaseack = channel.unary_unary(
                '/ArtistService/addTrgetArtistReleaseack',
                request_serializer=artist__pb2.GetArtistReleasesRequest.SerializeToString,
                response_deserializer=artist__pb2.GetArtistReleasesResponse.FromString,
                )


class ArtistServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getArtist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def addArtist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def addTrgetArtistReleaseack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArtistServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getArtist': grpc.unary_unary_rpc_method_handler(
                    servicer.getArtist,
                    request_deserializer=artist__pb2.GetArtistRequest.FromString,
                    response_serializer=artist__pb2.GetArtistResponse.SerializeToString,
            ),
            'addArtist': grpc.unary_unary_rpc_method_handler(
                    servicer.addArtist,
                    request_deserializer=artist__pb2.AddArtistRequest.FromString,
                    response_serializer=artist__pb2.AddArtistResponse.SerializeToString,
            ),
            'addTrgetArtistReleaseack': grpc.unary_unary_rpc_method_handler(
                    servicer.addTrgetArtistReleaseack,
                    request_deserializer=artist__pb2.GetArtistReleasesRequest.FromString,
                    response_serializer=artist__pb2.GetArtistReleasesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ArtistService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ArtistService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getArtist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ArtistService/getArtist',
            artist__pb2.GetArtistRequest.SerializeToString,
            artist__pb2.GetArtistResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def addArtist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ArtistService/addArtist',
            artist__pb2.AddArtistRequest.SerializeToString,
            artist__pb2.AddArtistResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def addTrgetArtistReleaseack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ArtistService/addTrgetArtistReleaseack',
            artist__pb2.GetArtistReleasesRequest.SerializeToString,
            artist__pb2.GetArtistReleasesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
