# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: artist.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61rtist.proto\"_\n\x06\x41rtist\x12\x11\n\tartist_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x61rtist_name\x18\x02 \x01(\t\x12\x12\n\nartist_url\x18\x03 \x01(\t\x12\x19\n\x11\x61rtist_updated_at\x18\x06 \x01(\t\"\x85\x01\n\x07Release\x12\x12\n\nrelease_id\x18\x01 \x01(\x05\x12\x15\n\rrelease_title\x18\x02 \x01(\t\x12\x14\n\x0crelease_date\x18\x03 \x01(\t\x12\x13\n\x0brelease_url\x18\x04 \x01(\t\x12\x10\n\x08label_id\x18\x05 \x01(\x05\x12\x12\n\nupdated_on\x18\x06 \x01(\t\"%\n\x10GetArtistRequest\x12\x11\n\tartist_id\x18\x01 \x01(\x05\";\n\x10\x41\x64\x64\x41rtistRequest\x12\x13\n\x0b\x61rtist_name\x18\x01 \x01(\t\x12\x12\n\nartist_url\x18\x02 \x01(\t\"-\n\x18GetArtistReleasesRequest\x12\x11\n\tartist_id\x18\x01 \x01(\x05\",\n\x11GetArtistResponse\x12\x17\n\x06\x41rtist\x18\x01 \x01(\x0b\x32\x07.Artist\",\n\x11\x41\x64\x64\x41rtistResponse\x12\x17\n\x06\x41rtist\x18\x01 \x01(\x0b\x32\x07.Artist\"7\n\x19GetArtistReleasesResponse\x12\x1a\n\x08Releases\x18\x01 \x03(\x0b\x32\x08.Release2\xca\x01\n\rArtistService\x12\x32\n\tgetArtist\x12\x11.GetArtistRequest\x1a\x12.GetArtistResponse\x12\x32\n\taddArtist\x12\x11.AddArtistRequest\x1a\x12.AddArtistResponse\x12Q\n\x18\x61\x64\x64TrgetArtistReleaseack\x12\x19.GetArtistReleasesRequest\x1a\x1a.GetArtistReleasesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'artist_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ARTIST']._serialized_start=16
  _globals['_ARTIST']._serialized_end=111
  _globals['_RELEASE']._serialized_start=114
  _globals['_RELEASE']._serialized_end=247
  _globals['_GETARTISTREQUEST']._serialized_start=249
  _globals['_GETARTISTREQUEST']._serialized_end=286
  _globals['_ADDARTISTREQUEST']._serialized_start=288
  _globals['_ADDARTISTREQUEST']._serialized_end=347
  _globals['_GETARTISTRELEASESREQUEST']._serialized_start=349
  _globals['_GETARTISTRELEASESREQUEST']._serialized_end=394
  _globals['_GETARTISTRESPONSE']._serialized_start=396
  _globals['_GETARTISTRESPONSE']._serialized_end=440
  _globals['_ADDARTISTRESPONSE']._serialized_start=442
  _globals['_ADDARTISTRESPONSE']._serialized_end=486
  _globals['_GETARTISTRELEASESRESPONSE']._serialized_start=488
  _globals['_GETARTISTRELEASESRESPONSE']._serialized_end=543
  _globals['_ARTISTSERVICE']._serialized_start=546
  _globals['_ARTISTSERVICE']._serialized_end=748
# @@protoc_insertion_point(module_scope)
