apiVersion: apps/v1
kind: Deployment
metadata:
  name: track-model-rs-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: track-model
  template:
    metadata:
      labels:
        app: track-model
    spec:
      containers:
      - name: track-model
        image: group02-track-model-service:latest
        imagePullPolicy: Never
            