apiVersion: apps/v1
kind: Deployment
metadata:
  name: genre-model-rs-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: genre-model
  template:
    metadata:
      labels:
        app: genre-model
    spec:
      containers:
      - name: genre-model
        image: group02-genre-model-service:latest
        imagePullPolicy: Never
       
            