BEGIN TRANSACTION;

CREATE TABLE Genres(
    genre_id SERIAL PRIMARY KEY NOT NULL,
    genre_name TEXT UNIQUE NOT NULL,
    song_count BIGINT NOT NULL,
    genre_url TEXT UNIQUE NOT NULL,
    updated_on DATE NOT NULL
);

COMMIT;