# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import track_pb2 as track__pb2


class TrackServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getTrack = channel.unary_unary(
                '/TrackService/getTrack',
                request_serializer=track__pb2.GetTrackRequest.SerializeToString,
                response_deserializer=track__pb2.GetTrackResponse.FromString,
                )
        self.deleteTrack = channel.unary_unary(
                '/TrackService/deleteTrack',
                request_serializer=track__pb2.DeleteTrackRequest.SerializeToString,
                response_deserializer=track__pb2.DeleteTrackResponse.FromString,
                )
        self.addTrack = channel.unary_unary(
                '/TrackService/addTrack',
                request_serializer=track__pb2.AddTrackRequest.SerializeToString,
                response_deserializer=track__pb2.AddTrackResponse.FromString,
                )
        self.getTrackGenre = channel.unary_unary(
                '/TrackService/getTrackGenre',
                request_serializer=track__pb2.GetTrackGenreRequest.SerializeToString,
                response_deserializer=track__pb2.GetTrackGenreResponse.FromString,
                )


class TrackServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getTrack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteTrack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def addTrack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getTrackGenre(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrackServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getTrack': grpc.unary_unary_rpc_method_handler(
                    servicer.getTrack,
                    request_deserializer=track__pb2.GetTrackRequest.FromString,
                    response_serializer=track__pb2.GetTrackResponse.SerializeToString,
            ),
            'deleteTrack': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteTrack,
                    request_deserializer=track__pb2.DeleteTrackRequest.FromString,
                    response_serializer=track__pb2.DeleteTrackResponse.SerializeToString,
            ),
            'addTrack': grpc.unary_unary_rpc_method_handler(
                    servicer.addTrack,
                    request_deserializer=track__pb2.AddTrackRequest.FromString,
                    response_serializer=track__pb2.AddTrackResponse.SerializeToString,
            ),
            'getTrackGenre': grpc.unary_unary_rpc_method_handler(
                    servicer.getTrackGenre,
                    request_deserializer=track__pb2.GetTrackGenreRequest.FromString,
                    response_serializer=track__pb2.GetTrackGenreResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TrackService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TrackService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getTrack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TrackService/getTrack',
            track__pb2.GetTrackRequest.SerializeToString,
            track__pb2.GetTrackResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteTrack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TrackService/deleteTrack',
            track__pb2.DeleteTrackRequest.SerializeToString,
            track__pb2.DeleteTrackResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def addTrack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TrackService/addTrack',
            track__pb2.AddTrackRequest.SerializeToString,
            track__pb2.AddTrackResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getTrackGenre(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TrackService/getTrackGenre',
            track__pb2.GetTrackGenreRequest.SerializeToString,
            track__pb2.GetTrackGenreResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
