SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
BEGIN TRANSACTION;

CREATE TABLE ArtistsReleases(
    artist_id BIGINT NOT NULL,
    release_id BIGINT NOT NULL,
    PRIMARY KEY (artist_id, release_id)
);

COMMIT;
