apiVersion: apps/v1
kind: Deployment
metadata:
  name: genre-logic-rs-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: genre-logic
  template:
    metadata:
      labels:
        app: genre-logic
    spec:
      containers:
      - name: genre-logic
        image: group02-genre-logic-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5002 